#index:
#    path: /
#    controller: App\Controller\DefaultController::index

Home:
  path: /home
  controller: App\Controller\HomeController::index

Back:
  path: /back
  controller: App\Controller\HomeController::indexBack
